Traceback (most recent call last):
  File "inference2.py", line 65, in <module>
    model=torch.load(path)
  File "/home/dbreen/miniconda3/envs/thesis/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/dbreen/miniconda3/envs/thesis/lib/python3.8/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/dbreen/miniconda3/envs/thesis/lib/python3.8/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/dbreen/miniconda3/envs/thesis/lib/python3.8/site-packages/torch/serialization.py", line 833, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
OSError: [Errno 5] Input/output error
